### ISSUE TITLE
Resource for `::` namespace operator and class constants.

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/oo-animal-sorter#2]
This lab makes use of `AnimalSorter::LAND_ANIMALS` so maybe include a paragraph or add another readme before this about the scope/namespace operator and using class constants.

**Comment by AnnJohn** [comment]
Iceboxing for now (but lab will be replaced soon)

**Comment by AnnJohn** [comment]
Closing issue since lab will be deprecated
