### ISSUE TITLE
Hardcoding data

### ISSUE THREAD

**Issue by EJLarcs** [learn-co-curriculum/oo-animal-sorter#7]
Hey guys, 

I just wanted to let you know that in some of the labs (in this one its where you have to insert the names of the animals hardcoded into the constant arrays) that it would be a real time saver to indicate where specific values can be directly inputted(hardcoded) simply because as students we are doing are best to not hardcode anything in the fear that we are cheating so you can waste a lot of time when in fact that is the case. 

Cheers,
Janey.

**Comment by AnnJohn** [comment]
Closing the issue since lab will no longer be used.
